version: '3.1'

services:
  ewm-service:
    build: ./main-service
    container_name: main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_NAME=exploreMain
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3061334
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/exploreMain

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: exploreMain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3061334

  stats-server:
    build: ./stats-service
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=exploreStats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3061334
      - DB_HOST=stats-db
      - DB_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreStats

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6543:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: exploreStats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3061334