version: '3.1'
services:
  stats-server:
    build: stats-service/
    image: stats
    container_name: stats-service
    depends_on:
      - ewm-service
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3061334

  stats-db:
    image: postgres:14-alpine
    container_name: explore-postgres
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3061334

  ewm-service:
    build: main-service/
    image: main
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3061334

  ewm-db:
    image: postgres:14-alpine
    container_name: explore-stats-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3061334
